"""Blender adapter for precomputed dry-basin states. No field or FEM equation runs here."""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path[:0] = [str(ROOT), str(ROOT / "src")]
_adapter = None
HANDLER_NAME = "dry_basin_frame_change"


def dry_basin_frame_change(scene, _depsgraph=None):
    """Display the supplied frame; the authoritative physical state was generated by Python."""
    if _adapter is None:
        return
    import numpy as np

    obj, bundle, markers, label = _adapter
    index = max(0, min(scene.frame_current - 1, len(bundle["times"]) - 1))
    gain = bundle["metadata"]["visual_gain"]
    coordinates = bundle["vertices"] + gain * bundle["displacements"][index]
    obj.data.vertices.foreach_set("co", np.asarray(coordinates, dtype=np.float32).ravel())
    obj.data.update()
    for i, (marker, offset) in enumerate(markers):
        marker.location = (
            bundle["marker_reference"][i] + gain * bundle["marker_displacements"][index, i] + offset
        )
    time = float(bundle["times"][index])
    scene["physical_time_s"] = time
    scene["retained_energy_j"] = float(bundle["energies"][index])
    label.data.body = f"DRY BASIN   t={time:.3f} s\nDisplacement x{gain:g}"


def build(bundle_path: Path, config_path: Path):
    """Build presentation around provided coordinates and add matching audio at frame one."""
    import bpy
    import numpy as np

    from spatial_sculptures.blender.camera import create_camera
    from spatial_sculptures.blender.geometry import add_sphere, create_mesh
    from spatial_sculptures.blender.lighting import area_light
    from spatial_sculptures.blender.materials import black_sensor, brushed_steel, dark_metal
    from spatial_sculptures.blender.utils import (
        HANDLER_TAG,
        add_cylinder,
        clear_scene,
        cylinder_between,
        set_smooth,
    )

    global _adapter
    config = json.loads(config_path.read_text())
    with np.load(bundle_path, allow_pickle=False) as archive:
        bundle = {name: archive[name].copy() for name in archive.files if name != "metadata"}
        bundle["metadata"] = json.loads(str(archive["metadata"]))
    if len(bundle["displacements"]) != bundle["metadata"]["frame_count"]:
        raise ValueError("Inconsistent visualization bundle frame count")
    clear_scene((HANDLER_NAME,))
    steel, metal, sensor = brushed_steel(), dark_metal(), black_sensor()
    cuts = np.r_[0, np.cumsum(bundle["face_sizes"])]
    faces = [bundle["face_indices"][a:b].tolist() for a, b in zip(cuts[:-1], cuts[1:], strict=True)]
    basin = create_mesh("Numerical dry basin", bundle["vertices"].tolist(), faces, steel)
    set_smooth(basin)
    modifier = basin.modifiers.new("Uniform physical thickness", "SOLIDIFY")
    modifier.thickness = config["thickness"]
    modifier.offset = 0
    markers = []
    for i, exciter in enumerate(config["exciters"]):
        position = bundle["marker_reference"][i].copy()
        offset = np.array([0.0, 0.0, -0.012 - config["thickness"] / 2])
        marker = add_cylinder(
            f"Rigid exciter housing {i + 1}",
            exciter["patch"]["width"] / 2,
            0.022,
            position + offset,
            metal,
            vertices=24,
        )
        markers.append((marker, offset))
    for i, _pickup in enumerate(config["pickups"]):
        index = i + len(config["exciters"])
        offset = np.array([0.0, 0.0, 0.012])
        marker = add_sphere(
            f"Virtual contact pickup {i + 1}",
            0.009,
            bundle["marker_reference"][index] + offset,
            sensor,
        )
        markers.append((marker, offset))
    for i, (x, y, z) in enumerate(bundle["support_reference"]):
        # Symbolic supports show placement; their compliance is in the numerical model.
        cylinder_between(
            f"Support {i + 1}",
            (x, y, 0.025),
            (x, y, z - config["thickness"] / 2),
            0.009,
            metal,
            vertices=16,
        )
    create_mesh("Floor", [(-3, -3, 0), (3, -3, 0), (3, 3, 0), (-3, 3, 0)], [(0, 1, 2, 3)])
    camera = create_camera("Dry basin camera", (1.9, -2.5, 1.95), (0, 0, 0.7), lens=48)
    area_light("Key", (1, -1, 3), (0, 0, 0.7), energy=700, size=3)
    area_light("Fill", (-2, 1, 2), (0, 0, 0.7), energy=400, size=2)
    label_data = bpy.data.curves.new("Physical-state label", "FONT")
    label = bpy.data.objects.new("Physical-state label", label_data)
    bpy.context.collection.objects.link(label)
    label.parent = camera
    label.location = (-0.58, 0.36, -2)
    label.scale = (0.035,) * 3
    label.data.size = 1
    scene = bpy.context.scene
    scene.render.engine = "BLENDER_WORKBENCH"
    scene.render.fps = config["fps"]
    scene.render.resolution_x, scene.render.resolution_y = config["resolution"]
    scene.render.resolution_percentage = 100
    scene.render.image_settings.file_format = "PNG"
    scene.frame_start, scene.frame_end = 1, bundle["metadata"]["frame_count"]
    scene.display.shading.light = "STUDIO"
    scene.display.shading.color_type = "MATERIAL"
    # Workbench otherwise projects the camera's text label as a shadow onto the basin.
    scene.display.shading.show_shadows = False
    scene.display.shading.background_type = "WORLD"
    scene.world.color = (0.14, 0.14, 0.14)
    scene["model"] = "Linear dry graph shell; no water, hydrophone pressure or radiated acoustics"
    scene["physical_configuration_json"] = json.dumps(config, sort_keys=True)
    scene["physical_seconds_per_visual_second"] = bundle["metadata"][
        "physical_seconds_per_visual_second"
    ]
    scene["presentation"] = bundle["metadata"]["presentation"]
    scene.sync_mode = (
        "AUDIO_SYNC" if scene["physical_seconds_per_visual_second"] == 1 else "FRAME_DROP"
    )
    if scene.sequence_editor:
        collection = (
            scene.sequence_editor.strips
            if hasattr(scene.sequence_editor, "strips")
            else scene.sequence_editor.sequences
        )
        for strip in list(collection):
            collection.remove(strip)
    if scene["physical_seconds_per_visual_second"] == 1:
        editor = scene.sequence_editor_create()
        collection = editor.strips if hasattr(editor, "strips") else editor.sequences
        sound = collection.new_sound(
            "Model contact-velocity audio",
            bundle["metadata"]["audio_path"],
            channel=1,
            frame_start=1,
        )
        sound.volume = 0.2
    for screen in bpy.data.screens:
        for area in screen.areas:
            if area.type == "VIEW_3D":
                area.spaces.active.shading.type = "SOLID"
                area.spaces.active.region_3d.view_perspective = "CAMERA"
    _adapter = (basin, bundle, markers, label)
    setattr(dry_basin_frame_change, HANDLER_TAG, True)
    bpy.app.handlers.frame_change_pre.append(dry_basin_frame_change)
    scene.frame_set(1)
    print(
        "Dry basin presentation ready. Press Space for playback; "
        "inspection view omits audio when slowed."
    )
    return basin


def main():
    import bpy

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bundle", type=Path, required=True)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--render-directory", type=Path)
    args = parser.parse_args(sys.argv[sys.argv.index("--") + 1 :] if "--" in sys.argv else [])
    build(args.bundle, args.config)
    if args.render_directory:
        args.render_directory.mkdir(parents=True, exist_ok=True)
        scene = bpy.context.scene
        scene.render.filepath = str(args.render_directory / "frame_")
        # Render the 3D scene; the sound strip is for interactive playback only.
        scene.render.use_sequencer = False
        bpy.ops.render.render(animation=True)


if __name__ == "__main__":
    main()
